name: Check final release

on:
  pull_request:
  release:
    types: [prereleased]

env:
  LAST_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
  RELEASE_TITLE: ${{ github.event.release.name }}
  
jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Verify dependencies files in a GA release
        run: ./.github/scripts/check-final-rc-deps.sh
